config/routes.rb
Rails.application.routes.draw do
  resources :electricity_readings
  resources :water_readings
  resources :bank_account_types
  resources :comunes
  resources :important_numerical_values
  resources :banks
  root 'index#index'

  resources :payment_methods
  resources :common_expense_payments
  resources :rent_payments
  resources :subunit_rents
  resources :outcome_categories
  resources :outcomes do
    collection do
      get 'history_outcomes_property/:property_id' => 'outcomes#history_outcomes_property', :as => :history_outcomes_property
      post 'search_outcomes_property_by_period', :as => :search_outcomes_property_by_period
    end
  end
  resources :common_expense_subunits do
    collection do
      get 'check_if_common_expense_property_for_period_is_issued' => 'common_expense_subunits#check_if_common_expense_property_for_period_is_issued'
    end
  end
  resources :common_expense_properties do
    collection do
      get 'history_common_expenses_property/:property_id' => 'common_expense_properties#history_common_expenses_property', :as => :history_common_expenses_property
      post 'search_common_expense_property_by_period', :as => :search_common_expense_property_by_period
    end
  end
  resources :subunits
  resources :properties do
    collection do
      get 'register_water_readings_for_subunits' => 'properties#register_water_readings_for_subunits', :as => :register_water_readings_for_subunits
      post 'create_water_readings_for_subunits' => 'properties#create_water_readings_for_subunits', :as => :create_water_readings_for_subunits
      get 'register_electricity_readings_for_subunits' => 'properties#register_electricity_readings_for_subunits', :as => :register_electricity_readings_for_subunits
      post 'create_electricity_readings_for_subunits' => 'properties#create_electricity_readings_for_subunits', :as => :create_electricity_readings_for_subunits
    end
  end
  resources :property_types

  devise_for :renters, controllers: {
    sessions: 'renters/sessions',
    registrations: 'renters/registrations'
  }
  devise_for :administrators, controllers: {
    sessions: 'administrators/sessions',
    registrations: 'administrators/registrations'
  }
  devise_for :owners, controllers: {
    sessions: 'owners/sessions',
    registrations: 'owners/registrations'
  }

  scope path: '/index', controller: :index do
    get 'index' => 'index#index', :as => :index
  end

  scope path: '/administrators', controller: :administrators do
    get 'dashboard' => 'administrators#dashboard', :as => :administrators_dashboard
    get 'new_subunit_for_property/:property_id' => 'administrators#new_subunit_for_property', :as => :new_subunit_for_property
    get 'new_matrix_common_expense_property/:property_id' => 'administrators#new_matrix_common_expense_property', :as => :new_matrix_common_expense_property
    get 'rent_for_subunits/:property_id' => 'administrators#rent_for_subunits', :as => :rent_for_subunits
    post 'create_rent_for_subunits' => 'administrators#create_rent_for_subunits', :as => :create_rent_for_subunits
    get 'renter_profile/:renter_id' => 'administrators#renter_profile', :as => :renter_profile
    get 'test_pdf_rent_charge' => 'administrators#test_pdf_rent_charge', :as => :test_pdf_rent_charge
    get 'test_pdf_common_expense_charge' => 'administrators#test_pdf_common_expense_charge', :as => :test_pdf_common_expense_charge
    get 'test_pdf_rent_receipt' => 'administrators#test_pdf_rent_receipt', :as => :test_pdf_rent_receipt
    get 'search_rent_charge', :as => :search_rent_charge
    get 'search_common_expense_subunit', :as => :search_common_expense_subunit
    post 'search_id_for_rent_charge' => 'administrators#search_id_for_rent_charge', :as => :search_id_for_rent_charge
    post 'search_id_for_common_expense_subunit' => 'administrators#search_id_for_common_expense_subunit', :as => :search_id_for_common_expense_subunit
    get 'check_if_common_expense_property_for_period_is_issued' => 'administrators#check_if_common_expense_property_for_period_is_issued'
    get 'edit_renter_profile/:id' => 'administrators#edit_renter_profile', :as => :edit_renter_profile
    get 'edit_owner_profile/:id' => 'administrators#edit_owner_profile', :as => :edit_owner_profile
    put 'update_renter_registry/:renter_id' => 'administrators#update_renter_registry', :as => :update_renter_registry
    put 'update_owner_registry/:owner_id' => 'administrators#update_owner_registry', :as => :update_owner_registry
  end

  scope path: '/renters', controller: :renters do
    get 'dashboard' => 'renters#dashboard', :as => :renters_dashboard
    get 'index' => 'renters#index', :as => :renters_index
    get 'subunits_for_renter', :as => :subunits_for_renter
    get 'properties_for_renter', :as => :properties_for_renter
  end

  scope path: '/owners', controller: :owners do
    get 'dashboard' => 'owners#dashboard', :as => :owners_dashboard
    get 'index' => 'owners#index', :as => :owners_index
    get 'subunits_for_owner', :as => :subunits_for_owner
    get 'properties_for_owner', :as => :properties_for_owner
  end
end

app/helpers/transversals_helper.rb
module TransversalsHelper
  def show_navbar
    if administrator_signed_in?
      render('transversals/navbar_admin')
    elsif renter_signed_in?
      render('transversals/navbar_renter')
    elsif owner_signed_in?
      render('transversals/navbar_owner')
    end
  end
end

app/views/transversals/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">PropGenius</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">acciones<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "crear propiedad", new_property_type_path %></li>
            <li><a href="#"><%= link_to "crear arrendatario", new_renter_registration_path %></a></li>
            <li><%= link_to "crear tipo propiedad", new_property_type_path %></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "cerrar sesión", destroy_administrator_session_path, :method => :delete %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/transversals/_navbar_admin.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "propgenius", administrators_dashboard_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">acciones<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="li-navbar"><%= link_to "crear propiedad", new_property_path %></li>
            <li class="li-navbar"><%= link_to "crear tipo propiedad", new_property_type_path %></li>
            <li role="separator" class="divider"></li>
            <li class="li-navbar"><a href="#"><%= link_to "crear arrendatario", new_renter_registration_path %></a></li>
            <li class="li-navbar"><a href="#"><%= link_to "crear propietario", new_owner_registration_path %></a></li>
          </ul>
        </li>
        <li class="li-navbar"><%= link_to "propiedades", properties_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="li-navbar"><%= link_to "cerrar sesión", destroy_administrator_session_path, :method => :delete %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/transversals/_navbar_owner.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "propgenius", administrators_dashboard_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">acciones<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="li-navbar"><%= link_to "crear propiedad", new_property_path %></li>
            <li class="li-navbar"><a href="#"><%= link_to "crear arrendatario", new_renter_registration_path %></a></li>
            <li class="li-navbar"><%= link_to "crear tipo propiedad", new_property_type_path %></li>
            <li role="separator" class="divider"></li>
            <li class="li-navbar"><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li class="li-navbar"><a href="#">One more separated link</a></li>
          </ul>
        </li>
        <li class="li-navbar"><%= link_to "propiedades", properties_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="li-navbar"><%= link_to "cerrar sesión", destroy_administrator_session_path, :method => :delete %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/transversals/_navbar_renter.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "propgenius", renters_dashboard_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "cerrar sesión", destroy_renter_session_path, :method => :delete %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>