config/routes.rb
Rails.application.routes.draw do
  resources :electricity_readings
  resources :water_readings
  resources :bank_account_types
  resources :comunes
  resources :important_numerical_values
  resources :banks
  root 'index#index'

  resources :payment_methods
  resources :common_expense_payments
  resources :rent_payments
  resources :subunit_rents
  resources :outcome_categories
  resources :outcomes do
    collection do
      get 'history_outcomes_property/:property_id' => 'outcomes#history_outcomes_property', :as => :history_outcomes_property
      post 'search_outcomes_property_by_period', :as => :search_outcomes_property_by_period
    end
  end
  resources :common_expense_subunits do
    collection do
      get 'check_if_common_expense_property_for_period_is_issued' => 'common_expense_subunits#check_if_common_expense_property_for_period_is_issued'
    end
  end
  resources :common_expense_properties do
    collection do
      get 'history_common_expenses_property/:property_id' => 'common_expense_properties#history_common_expenses_property', :as => :history_common_expenses_property
      post 'search_common_expense_property_by_period', :as => :search_common_expense_property_by_period
    end
  end
  resources :subunits
  resources :properties do
    collection do
      get 'register_water_readings_for_subunits' => 'properties#register_water_readings_for_subunits', :as => :register_water_readings_for_subunits
      post 'create_water_readings_for_subunits' => 'properties#create_water_readings_for_subunits', :as => :create_water_readings_for_subunits
      get 'register_electricity_readings_for_subunits' => 'properties#register_electricity_readings_for_subunits', :as => :register_electricity_readings_for_subunits
      post 'create_electricity_readings_for_subunits' => 'properties#create_electricity_readings_for_subunits', :as => :create_electricity_readings_for_subunits
    end
  end
  resources :property_types

  devise_for :renters, controllers: {
    sessions: 'renters/sessions',
    registrations: 'renters/registrations'
  }
  devise_for :administrators, controllers: {
    sessions: 'administrators/sessions',
    registrations: 'administrators/registrations'
  }
  devise_for :owners, controllers: {
    sessions: 'owners/sessions',
    registrations: 'owners/registrations'
  }

  scope path: '/index', controller: :index do
    get 'index' => 'index#index', :as => :index
  end

  scope path: '/administrators', controller: :administrators do
    get 'dashboard' => 'administrators#dashboard', :as => :administrators_dashboard
    get 'new_subunit_for_property/:property_id' => 'administrators#new_subunit_for_property', :as => :new_subunit_for_property
    get 'new_matrix_common_expense_property/:property_id' => 'administrators#new_matrix_common_expense_property', :as => :new_matrix_common_expense_property
    get 'rent_for_subunits/:property_id' => 'administrators#rent_for_subunits', :as => :rent_for_subunits
    post 'create_rent_for_subunits' => 'administrators#create_rent_for_subunits', :as => :create_rent_for_subunits
    get 'renter_profile/:renter_id' => 'administrators#renter_profile', :as => :renter_profile
    get 'test_pdf_rent_charge' => 'administrators#test_pdf_rent_charge', :as => :test_pdf_rent_charge
    get 'test_pdf_common_expense_charge' => 'administrators#test_pdf_common_expense_charge', :as => :test_pdf_common_expense_charge
    get 'test_pdf_rent_receipt' => 'administrators#test_pdf_rent_receipt', :as => :test_pdf_rent_receipt
    get 'search_rent_charge', :as => :search_rent_charge
    get 'search_common_expense_subunit', :as => :search_common_expense_subunit
    post 'search_id_for_rent_charge' => 'administrators#search_id_for_rent_charge', :as => :search_id_for_rent_charge
    post 'search_id_for_common_expense_subunit' => 'administrators#search_id_for_common_expense_subunit', :as => :search_id_for_common_expense_subunit
    get 'check_if_common_expense_property_for_period_is_issued' => 'administrators#check_if_common_expense_property_for_period_is_issued'
    get 'edit_renter_profile/:id' => 'administrators#edit_renter_profile', :as => :edit_renter_profile
    get 'edit_owner_profile/:id' => 'administrators#edit_owner_profile', :as => :edit_owner_profile
    put 'update_renter_registry/:renter_id' => 'administrators#update_renter_registry', :as => :update_renter_registry
    put 'update_owner_registry/:owner_id' => 'administrators#update_owner_registry', :as => :update_owner_registry
  end

  scope path: '/renters', controller: :renters do
    get 'dashboard' => 'renters#dashboard', :as => :renters_dashboard
    get 'index' => 'renters#index', :as => :renters_index
    get 'subunits_for_renter', :as => :subunits_for_renter
    get 'properties_for_renter', :as => :properties_for_renter
  end

  scope path: '/owners', controller: :owners do
    get 'dashboard' => 'owners#dashboard', :as => :owners_dashboard
    get 'index' => 'owners#index', :as => :owners_index
    get 'subunits_for_owner', :as => :subunits_for_owner
    get 'properties_for_owner', :as => :properties_for_owner
  end
end

app/models/outcome_category.rb
class OutcomeCategory < ActiveRecord::Base
  has_many :outcomes
end

app/controllers/outcome_categories_controller.rb
class OutcomeCategoriesController < ApplicationController
  before_action :set_outcome_category, only: [:show, :edit, :update, :destroy]

  # GET /outcome_categories
  # GET /outcome_categories.json
  def index
    @outcome_categories = OutcomeCategory.all
  end

  # GET /outcome_categories/1
  # GET /outcome_categories/1.json
  def show
  end

  # GET /outcome_categories/new
  def new
    @outcome_category = OutcomeCategory.new
  end

  # GET /outcome_categories/1/edit
  def edit
  end

  # POST /outcome_categories
  # POST /outcome_categories.json
  def create
    @outcome_category = OutcomeCategory.new(outcome_category_params)

    respond_to do |format|
      if @outcome_category.save
        format.html { redirect_to @outcome_category, notice: 'Outcome category was successfully created.' }
        format.json { render :show, status: :created, location: @outcome_category }
      else
        format.html { render :new }
        format.json { render json: @outcome_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outcome_categories/1
  # PATCH/PUT /outcome_categories/1.json
  def update
    respond_to do |format|
      if @outcome_category.update(outcome_category_params)
        format.html { redirect_to @outcome_category, notice: 'Outcome category was successfully updated.' }
        format.json { render :show, status: :ok, location: @outcome_category }
      else
        format.html { render :edit }
        format.json { render json: @outcome_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outcome_categories/1
  # DELETE /outcome_categories/1.json
  def destroy
    @outcome_category.destroy
    respond_to do |format|
      format.html { redirect_to outcome_categories_url, notice: 'Outcome category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outcome_category
      @outcome_category = OutcomeCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outcome_category_params
      params.require(:outcome_category).permit(:name)
    end
end

app/helpers/outcome_categories_helper.rb
module OutcomeCategoriesHelper
end

app/views/outcome_categories/_form.html.erb
<%= form_for(@outcome_category) do |f| %>
  <% if @outcome_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outcome_category.errors.count, "error") %> prohibited this outcome_category from being saved:</h2>

      <ul>
      <% @outcome_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outcome_categories/edit.html.erb
<h1>Editing Outcome Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @outcome_category %> |
<%= link_to 'Back', outcome_categories_path %>

app/views/outcome_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Outcome Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @outcome_categories.each do |outcome_category| %>
      <tr>
        <td><%= outcome_category.name %></td>
        <td><%= link_to 'Show', outcome_category %></td>
        <td><%= link_to 'Edit', edit_outcome_category_path(outcome_category) %></td>
        <td><%= link_to 'Destroy', outcome_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Outcome category', new_outcome_category_path %>

app/views/outcome_categories/new.html.erb
<h1>New Outcome Category</h1>

<%= render 'form' %>

<%= link_to 'Back', outcome_categories_path %>

app/views/outcome_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @outcome_category.name %>
</p>

<%= link_to 'Edit', edit_outcome_category_path(@outcome_category) %> |
<%= link_to 'Back', outcome_categories_path %>