config/routes.rb
Rails.application.routes.draw do
  resources :electricity_readings
  resources :water_readings
  resources :bank_account_types
  resources :comunes
  resources :important_numerical_values
  resources :banks
  root 'index#index'

  resources :payment_methods
  resources :common_expense_payments
  resources :rent_payments
  resources :subunit_rents
  resources :outcome_categories
  resources :outcomes do
    collection do
      get 'history_outcomes_property/:property_id' => 'outcomes#history_outcomes_property', :as => :history_outcomes_property
      post 'search_outcomes_property_by_period', :as => :search_outcomes_property_by_period
    end
  end
  resources :common_expense_subunits do
    collection do
      get 'check_if_common_expense_property_for_period_is_issued' => 'common_expense_subunits#check_if_common_expense_property_for_period_is_issued'
    end
  end
  resources :common_expense_properties do
    collection do
      get 'history_common_expenses_property/:property_id' => 'common_expense_properties#history_common_expenses_property', :as => :history_common_expenses_property
      post 'search_common_expense_property_by_period', :as => :search_common_expense_property_by_period
    end
  end
  resources :subunits
  resources :properties do
    collection do
      get 'register_water_readings_for_subunits' => 'properties#register_water_readings_for_subunits', :as => :register_water_readings_for_subunits
      post 'create_water_readings_for_subunits' => 'properties#create_water_readings_for_subunits', :as => :create_water_readings_for_subunits
      get 'register_electricity_readings_for_subunits' => 'properties#register_electricity_readings_for_subunits', :as => :register_electricity_readings_for_subunits
      post 'create_electricity_readings_for_subunits' => 'properties#create_electricity_readings_for_subunits', :as => :create_electricity_readings_for_subunits
    end
  end
  resources :property_types

  devise_for :renters, controllers: {
    sessions: 'renters/sessions',
    registrations: 'renters/registrations'
  }
  devise_for :administrators, controllers: {
    sessions: 'administrators/sessions',
    registrations: 'administrators/registrations'
  }
  devise_for :owners, controllers: {
    sessions: 'owners/sessions',
    registrations: 'owners/registrations'
  }

  scope path: '/index', controller: :index do
    get 'index' => 'index#index', :as => :index
  end

  scope path: '/administrators', controller: :administrators do
    get 'dashboard' => 'administrators#dashboard', :as => :administrators_dashboard
    get 'new_subunit_for_property/:property_id' => 'administrators#new_subunit_for_property', :as => :new_subunit_for_property
    get 'new_matrix_common_expense_property/:property_id' => 'administrators#new_matrix_common_expense_property', :as => :new_matrix_common_expense_property
    get 'rent_for_subunits/:property_id' => 'administrators#rent_for_subunits', :as => :rent_for_subunits
    post 'create_rent_for_subunits' => 'administrators#create_rent_for_subunits', :as => :create_rent_for_subunits
    get 'renter_profile/:renter_id' => 'administrators#renter_profile', :as => :renter_profile
    get 'test_pdf_rent_charge' => 'administrators#test_pdf_rent_charge', :as => :test_pdf_rent_charge
    get 'test_pdf_common_expense_charge' => 'administrators#test_pdf_common_expense_charge', :as => :test_pdf_common_expense_charge
    get 'test_pdf_rent_receipt' => 'administrators#test_pdf_rent_receipt', :as => :test_pdf_rent_receipt
    get 'search_rent_charge', :as => :search_rent_charge
    get 'search_common_expense_subunit', :as => :search_common_expense_subunit
    post 'search_id_for_rent_charge' => 'administrators#search_id_for_rent_charge', :as => :search_id_for_rent_charge
    post 'search_id_for_common_expense_subunit' => 'administrators#search_id_for_common_expense_subunit', :as => :search_id_for_common_expense_subunit
    get 'check_if_common_expense_property_for_period_is_issued' => 'administrators#check_if_common_expense_property_for_period_is_issued'
    get 'edit_renter_profile/:id' => 'administrators#edit_renter_profile', :as => :edit_renter_profile
    get 'edit_owner_profile/:id' => 'administrators#edit_owner_profile', :as => :edit_owner_profile
    put 'update_renter_registry/:renter_id' => 'administrators#update_renter_registry', :as => :update_renter_registry
    put 'update_owner_registry/:owner_id' => 'administrators#update_owner_registry', :as => :update_owner_registry
  end

  scope path: '/renters', controller: :renters do
    get 'dashboard' => 'renters#dashboard', :as => :renters_dashboard
    get 'index' => 'renters#index', :as => :renters_index
    get 'subunits_for_renter', :as => :subunits_for_renter
    get 'properties_for_renter', :as => :properties_for_renter
  end

  scope path: '/owners', controller: :owners do
    get 'dashboard' => 'owners#dashboard', :as => :owners_dashboard
    get 'index' => 'owners#index', :as => :owners_index
    get 'subunits_for_owner', :as => :subunits_for_owner
    get 'properties_for_owner', :as => :properties_for_owner
  end
end

app/models/subunit.rb
class Subunit < ActiveRecord::Base
  before_create :set_lease_end_date
  before_create :set_readjustment_date

  belongs_to :owner
  belongs_to :renter
  belongs_to :property
  belongs_to :property_type
  has_many :common_expense_subunits
  has_many :rent_payments
  has_many :common_expense_payments
  has_many :subunit_rents
  has_many :water_readings
  has_many :electricity_readings

  def address_and_number
    "#{self.property.address}, Nº#{self.number}"
  end

  def set_lease_end_date
    self.lease_end_date = self.lease_startdate + self.lease_duration.months
  end

  def set_readjustment_date
    self.readjustment_date = self.lease_startdate + self.readjustment_months_period.months
  end

  def payments_status_ok
    if self.subunit_rents.where(payed: false).count >= 1
      return false
    else
      return true
    end
  end

  # Notifications
  # Lease
  def self.notify_when_thirty_to_end_lease
    @subunits = Subunit.where(lease_end_date: Date.today + 30.days)

    @subunits.each do |s|
      NotificationsForEndings.mailer_for_thirty_days(s.id).deliver
    end
  end

  def self.notify_when_fifteen_to_end_lease
    Subunit.where(lease_end_date: Date.today + 15.days)

    @subunits.each do |s|
      NotificationsForEndings.mailer_for_fifteen_days(s.id).deliver
    end
  end

  def self.notify_when_five_to_end_lease
    Subunit.where(lease_end_date: Date.today + 5.days)

    @subunits.each do |s|
      NotificationsForEndings.mailer_for_five_days(s.id).deliver
    end
  end

  def self.notify_when_one_to_end_lease
    Subunit.where(lease_end_date: Date.today + 1.days)

    @subunits.each do |s|
      NotificationsForEndings.mailer_for_one_days(s.id).deliver
    end
  end

  # Readjust
end

app/controllers/subunits_controller.rb
class SubunitsController < ApplicationController
  before_action :set_subunit, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_owner_administrator_renter

  # GET /subunits
  # GET /subunits.json
  def index
    @subunits = Subunit.all.order(number: :asc)
  end

  # GET /subunits/1
  # GET /subunits/1.json
  def show
    id = params[:id]
    @common_expenses = @subunit.common_expense_subunits.order(period: :desc)
    @subunit_rents = @subunit.subunit_rents.order(period: :desc)
    @water_readings = @subunit.water_readings
    @electricity_readings = @subunit.electricity_readings

    # Create array with water deltas
    @water_deltas = @water_readings.map { |wr| wr.get_consumption_delta }
    @electricity_deltas = @electricity_readings.map { |er| er.get_consumption_delta }
  end

  # GET /subunits/new
  def new
    @subunit = Subunit.new
  end

  # GET /subunits/1/edit
  def edit
  end

  # POST /subunits
  # POST /subunits.json
  def create
    @subunit = Subunit.new(subunit_params)

    respond_to do |format|
      if @subunit.save
        redirect_to property_path(@subunit.property.id)
        return
      else
        format.html { render :new }
        format.json { render json: @subunit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subunits/1
  # PATCH/PUT /subunits/1.json
  def update
    respond_to do |format|
      if @subunit.update(subunit_params)
        format.html { redirect_to @subunit, notice: 'Subunit was successfully updated.' }
        format.json { render :show, status: :ok, location: @subunit }
      else
        format.html { render :edit }
        format.json { render json: @subunit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subunits/1
  # DELETE /subunits/1.json
  def destroy
    @subunit.destroy
    respond_to do |format|
      format.html { redirect_to subunits_url, notice: 'Subunit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subunit
      @subunit = Subunit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subunit_params
      params.require(:subunit).permit(:square_meters, :property_type_id, :renter_id, :rent_value, :number, :lease_startdate, :owner_id, :property_id, :proration_percentage, :lease_duration, :lease_end_date, :readjustment_percentage, :readjustment_months_period, :charge_iva, :charge_uf, :generate_for_subunits)
    end
end

app/helpers/subunits_helper.rb
module SubunitsHelper
end

app/views/subunits/_actions_for_subunit.html.erb
<div class="holder-extern">
    <div class="holder-intern">
        <div class="text-center">
            <%= inline_svg("document.svg", {class: "chart"}) %>
        </div>
        <%= link_to "GASTO COMÚN", new_common_expense_subunit_path(:subunit_id => @subunit.id), class: "btn btn-default btn-block action-button faded-button" %>
        <%= link_to "ARRIENDO", new_subunit_rent_path(:subunit_id => @subunit.id), class: "btn btn-default btn-block action-button aquamarine-button" %>
    </div>
</div>

app/views/subunits/_form.html.erb
<%= form_for(@subunit) do |f| %>
  <% if @subunit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subunit.errors.count, "error") %> prohibited this subunit from being saved:</h2>

      <ul>
      <% @subunit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :square_meters %><br>
    <%= f.text_field :square_meters %>
  </div>
  <div class="field">
    <%= f.label :property_type_id %><br>
    <%= f.number_field :property_type_id %>
  </div>
  <div class="field">
    <%= f.label :renter_id %><br>
    <%= f.number_field :renter_id %>
  </div>
  <div class="field">
    <%= f.label :proration_percentage %><br>
    <%= f.number_field :proration_percentage %>
  </div>
  <div class="field">
    <%= f.label :rent_value %><br>
    <%= f.text_field :rent_value %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :lease_startdate %><br>
    <%= f.date_select :lease_startdate %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br>
    <%= f.number_field :owner_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subunits/_water_and_electricity_readings.html.erb
<div class="holder-extern-no-verticality">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 fifty-percent-height vertical-center">
        <div>
            <div class="text-center">
                <%= inline_svg("water.svg", {class: "water"}) %>
            </div>
            <%= link_to "REGISTRO MEDIDOR AGUA", new_water_reading_path(:subunit_id => @subunit.id), class: "btn btn-default action-button blue-button" %>
        </div>
    </div>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 fifty-percent-height vertical-center">
        <div>
            <div class="text-center holder-action-button">
                <%= inline_svg("thunder.svg", {class: "house"}) %>
            </div>
            <%= link_to "REGISTRO MEDIDOR LUZ", new_electricity_reading_path(:subunit_id => @subunit.id), class: "btn btn-default action-button golden-button" %>
        </div>
    </div>
</div>

app/views/subunits/index.html.erb
<h1 class="text-center">Listado de Subunidades</h1>

<div class="container-fluid">
    <div class="col-lg-12 col-md-12 col-sm-12 info-square">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th class="table-header">DIRECCIÓN</th>
                        <th class="table-header">M2</th>
                        <th class="table-header">TIPO</th>
                        <th class="table-header">ARRENDADOR</th>
                        <th class="table-header">$</th>
                        <th class="table-header">Nº</th>
                        <th class="table-header">INICIO</th>
                        <th class="table-header">PROPIETARIO</th>
                        <th colspan="3"></th>
                    </tr>
                </thead>

                <tbody>
                    <% @subunits.each do |subunit| %>
                    <tr>
                        <td class="table-data"><%= link_to subunit.address_and_number, subunit_path(subunit) %></td>
                        <td class="table-data"><%= subunit.square_meters %></td>
                        <td class="table-data"><%= subunit.property_type.description %></td>
                        <td class="table-data"><%= link_to subunit.renter.renter_name_lastname, renter_profile_path(subunit.renter) %></td>
                        <% if subunit.charge_uf %>
                        <td class="table-data">UF: <%= subunit.rent_value %></td>
                        <% else %>
                        <td class="table-data">CLP: <%= number_to_currency(subunit.rent_value, delimiter: ".", precision: 0) %></td>
                        <% end %>
                        <td class="table-data"><%= subunit.number %></td>
                        <td class="table-data"><%= subunit.lease_startdate.strftime("%d/%m/%Y") %></td>
                        <td class="table-data"><%= subunit.owner.owner_name_lastname %></td>
                        <td class="table-data"><%= link_to 'MOSTRAR', subunit %></td>
                        <td class="table-data"><%= link_to 'EDITAR', edit_subunit_path(subunit) %></td>
                        <td class="table-data"><%= link_to 'ELIMINAR', subunit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/subunits/new.html.erb
<h1>New Subunit</h1>

<%= render 'form' %>

<%= link_to 'Back', subunits_path %>

app/views/subunits/show.html.erb
<div class="sub-nav"></div>
<div class="container-fluid container-squares">
    <div class="col-lg-4 col-md-3 info-square">
        <div class="holder-extern">
            <div class="holder-intern">
                <h2 class="text-center"><%= @subunit.address_and_number %></h2>
                <h3 class="text-center header-nav">Arrendador:
                    <%= @subunit.renter.renter_or_company_or_both %></h3>
                <h4 class="text-center alert-header"><%= "Hasta #{@subunit.lease_end_date.strftime("%d/%m/%Y")}" %></h4>
                <!-- <h4 class="text-center"><%= @subunit.renter.email %></h4> -->
                <h3 class="text-center header-nav"><%= "#{@subunit.square_meters} m2" %></h3>
                <% if administrator_signed_in? %>
                <h5 class="text-center"><%= link_to "EDITAR SUBUNIDAD", edit_subunit_path(@subunit), class: "btn btn-default action-button chet-button" %></h5>
                <% end %>
            </div>
        </div>
    </div>

    <% if administrator_signed_in? %>
    <div class="col-lg-4 col-md-3 info-square">
        <%= render('actions_for_subunit') %>
    </div>
    <% end %>

    <% if renter_signed_in? || owner_signed_in? %>
    <div class="col-lg-4 col-md-3 info-square">
        <div class="holder-extern">
            <div class="holder-intern">
              <div class="text-center">
                  <%= inline_svg("house.svg", {class: "chart"}) %>
              </div>
              <%= link_to "VER PROPIEDAD", property_path(@subunit.property), class: "btn btn-default btn-block action-button faded-button" %>
            </div>
        </div>
    </div>
    <% end %>

    <% if renter_signed_in? || owner_signed_in? %>
    <div class="col-lg-4 col-md-6 col-sm-6 info-square" id="map-holder">
        <div class="holder-extern-no-verticality" id="subunit_map_square"></div>
    </div>
    <% end %>

    <% if administrator_signed_in? %>
    <div class="col-lg-4 col-md-3 info-square">
        <%= render('subunits/water_and_electricity_readings') %>
    </div>
    <% end %>
    <div class="col-lg-6 col-md-9 info-square">
        <div class="holder-extern-no-verticality table-div">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th class="table-header">PERIODO</th>
                            <th class="table-header">#</th>
                            <th class="table-header">MONTO</th>
                            <th class="table-header">CUPÓN</th>
                            <th class="table-header">PAGADO</th>
                            <th class="table-header">MORA</th>
                            <th colspan="2"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @subunit_rents.each do |s| %>
                        <tr>
                            <td class="table-data"><%= s.period.strftime("%m/%Y") %></td>
                            <td class="table-data"><%= link_to s.id, subunit_rent_path(s.id) %></td>
                            <td class="table-data"><%= number_to_currency(s.amount, :precision => 0, :delimiter => ".") %></td>
                            <% if s.receipt.file? %>
                            <td class="table-data"><%= link_to "VER CUPÓN", s.receipt.url %></td>
                        <% else %>
                            <td class="table-data">SIN CUPÓN</td>
                            <% end %>
                            <% if s.payed? %>
                            <td class="table-data"><%= link_to "SI", s.rent_payment.receipt.url, class: "payed-rent" %></td>
                        <% else %>
                            <td class="table-data not-payed-rent">NO</td>
                            <td class="table-data"><%= number_to_currency(s.get_overdue_charge, :precision => 0, :delimiter => ".") %></td>
                            <% end %>
                            <% if !s.payed? %>
                            <% if administrator_signed_in? %>
                            <td class="table-data"><%= link_to "PAGAR", new_rent_payment_path(:subunit_rent_id => s.id) %></td>
                            <% end %>
                        <% else %>
                            <td class="table-data"><%= number_to_currency(0, :precision => 0, :delimiter => ".") %></td>
                            <% if administrator_signed_in? %>
                            <td class="table-data"><%= link_to "EDITAR", edit_rent_payment_path(s.rent_payment, :subunit_rent_id => s.id) %></td>
                            <% end %>
                            <td class="table-data"><%= link_to "DETALLE", rent_payment_path(s.rent_payment) %></td>
                            <% end %>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-6 col-md-9 info-square">
        <div class="holder-extern-no-verticality table-div">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th class="table-header">PERIODO</th>
                            <th class="table-header">#</th>
                            <th class="table-header">TOTAL</th>
                            <th class="table-header">CUPÓN</th>
                            <th class="table-header">PAGADO</th>
                            <th colspan="2"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @common_expenses.each do |c| %>
                        <tr>
                            <td class="table-data"><%= c.period.strftime("%m/%Y") %></td>
                            <td class="table-data"><%= c.id %></td>
                            <td class="table-data"><%= number_to_currency(c.total, :precision => 0, :delimiter => ".") %></td>
                            <% if c.receipt.file? %>
                            <td class="table-data"><%= link_to "VER CUPÓN", c.receipt.url %></td>
                        <% else %>
                            <td class="table-data">SIN CUPÓN</td>
                            <% end %>
                            <% if c.payed? %>
                            <td class="table-data"><%= link_to "SI", c.common_expense_payment.receipt.url, class: "payed-rent" %></td>
                        <% else %>
                            <td class="table-data not-payed-rent">NO</td>
                            <% end %>
                            <% if !c.payed? %>
                            <% if administrator_signed_in? %>
                            <td class="table-data"><%= link_to "PAGAR", new_common_expense_payment_path(:common_expense_subunit_id => c.id) %></td>
                            <% end %>
                        <% else %>
                            <% if administrator_signed_in? %>
                            <td class="table-data"><%= link_to "EDITAR", edit_common_expense_payment_path(c.common_expense_payment, :common_expense_subunit_id => c.id) %></td>
                            <% end %>
                            <td class="table-data"><%= link_to "DETALLE", common_expense_payment_path(c.common_expense_payment) %></td>
                            <% end %>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-3 info-square">
        <div class="holder-extern-no-verticality table-div">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th class="table-header">PERIODO</th>
                            <th class="table-header">TOTAL</th>
                            <th class="table-header">DELTA</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @water_readings.order(period: :desc).each do |w| %>
                        <tr>
                            <td class="table-data"><%= w.period %></td>
                            <td class="table-data"><%= w.total_reading %></td>
                            <td class="table-data"><%= w.get_consumption_delta %></td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-8 col-md-3 info-square">
        <div class="holder-extern">
            <div class="chart-holder">
                <canvas id="water_consumption_history"></canvas>
            </div>
        </div>
    </div>
    <div class="col-lg-8 col-md-3 info-square">
        <div class="holder-extern">
            <div class="chart-holder">
                <canvas id="electricity_consumption_history"></canvas>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-3 info-square">
        <div class="holder-extern-no-verticality table-div">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th class="table-header">PERIODO</th>
                            <th class="table-header">TOTAL</th>
                            <th class="table-header">DELTA</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @electricity_readings.order(period: :desc).each do |e| %>
                        <tr>
                            <td class="table-data"><%= e.period %></td>
                            <td class="table-data"><%= e.total_reading %></td>
                            <td class="table-data"><%= e.get_consumption_delta %></td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).on('turbolinks:load', function () {
        var ctx = document.getElementById("water_consumption_history");
        var date = new Date();
        var dataArray = <%= raw @water_deltas.to_json %>;
        if (ctx) {
            var myChart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: <%= raw @water_readings.map { |wr| wr.period.strftime("%m/%Y").to_json }  %>,
                    datasets: [
                        {
                            label: '∆ CONSUMO DE AGUA',
                            data: dataArray,
                            backgroundColor: 'RGBA(56, 87, 227, 0.2)',
                            borderColor: 'RGBA(56, 87, 227, 1.00)',
                            borderWidth: 1
                        }
                    ]
                },
                options: {
                    responsive: true,
                    scales: {
                        yAxes: [
                            {
                                ticks: {
                                    beginAtZero: true
                                }
                            }
                        ]
                    }
                }
            });
        }
    });
</script>
<script>
    $(document).on('turbolinks:load', function () {
        var ctx = document.getElementById("electricity_consumption_history");
        var date = new Date();
        var dataArray = <%= raw @electricity_deltas.to_json %>;
        var monthNames = ["ENE", "FEB"]
        if (ctx) {
            var myChart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: <%= raw @electricity_readings.map { |er| er.period.strftime("%m/%Y").to_json }  %>,
                    datasets: [
                        {
                            label: '∆ CONSUMO DE ELECTRICIDAD',
                            data: dataArray,
                            backgroundColor: 'RGBA(250, 219, 131, 0.2)',
                            borderColor: 'RGBA(250, 219, 131, 1.00)',
                            borderWidth: 1
                        }
                    ]
                },
                options: {
                    responsive: true,
                    scales: {
                        yAxes: [
                            {
                                ticks: {
                                    beginAtZero: true
                                }
                            }
                        ]
                    }
                }
            });
        }
    });
</script>