config/routes.rb
Rails.application.routes.draw do
  resources :electricity_readings
  resources :water_readings
  resources :bank_account_types
  resources :comunes
  resources :important_numerical_values
  resources :banks
  root 'index#index'

  resources :payment_methods
  resources :common_expense_payments
  resources :rent_payments
  resources :subunit_rents
  resources :outcome_categories
  resources :outcomes do
    collection do
      get 'history_outcomes_property/:property_id' => 'outcomes#history_outcomes_property', :as => :history_outcomes_property
      post 'search_outcomes_property_by_period', :as => :search_outcomes_property_by_period
    end
  end
  resources :common_expense_subunits do
    collection do
      get 'check_if_common_expense_property_for_period_is_issued' => 'common_expense_subunits#check_if_common_expense_property_for_period_is_issued'
    end
  end
  resources :common_expense_properties do
    collection do
      get 'history_common_expenses_property/:property_id' => 'common_expense_properties#history_common_expenses_property', :as => :history_common_expenses_property
      post 'search_common_expense_property_by_period', :as => :search_common_expense_property_by_period
    end
  end
  resources :subunits
  resources :properties do
    collection do
      get 'register_water_readings_for_subunits' => 'properties#register_water_readings_for_subunits', :as => :register_water_readings_for_subunits
      post 'create_water_readings_for_subunits' => 'properties#create_water_readings_for_subunits', :as => :create_water_readings_for_subunits
      get 'register_electricity_readings_for_subunits' => 'properties#register_electricity_readings_for_subunits', :as => :register_electricity_readings_for_subunits
      post 'create_electricity_readings_for_subunits' => 'properties#create_electricity_readings_for_subunits', :as => :create_electricity_readings_for_subunits
    end
  end
  resources :property_types

  devise_for :renters, controllers: {
    sessions: 'renters/sessions',
    registrations: 'renters/registrations'
  }
  devise_for :administrators, controllers: {
    sessions: 'administrators/sessions',
    registrations: 'administrators/registrations'
  }
  devise_for :owners, controllers: {
    sessions: 'owners/sessions',
    registrations: 'owners/registrations'
  }

  scope path: '/index', controller: :index do
    get 'index' => 'index#index', :as => :index
  end

  scope path: '/administrators', controller: :administrators do
    get 'dashboard' => 'administrators#dashboard', :as => :administrators_dashboard
    get 'new_subunit_for_property/:property_id' => 'administrators#new_subunit_for_property', :as => :new_subunit_for_property
    get 'new_matrix_common_expense_property/:property_id' => 'administrators#new_matrix_common_expense_property', :as => :new_matrix_common_expense_property
    get 'rent_for_subunits/:property_id' => 'administrators#rent_for_subunits', :as => :rent_for_subunits
    post 'create_rent_for_subunits' => 'administrators#create_rent_for_subunits', :as => :create_rent_for_subunits
    get 'renter_profile/:renter_id' => 'administrators#renter_profile', :as => :renter_profile
    get 'test_pdf_rent_charge' => 'administrators#test_pdf_rent_charge', :as => :test_pdf_rent_charge
    get 'test_pdf_common_expense_charge' => 'administrators#test_pdf_common_expense_charge', :as => :test_pdf_common_expense_charge
    get 'test_pdf_rent_receipt' => 'administrators#test_pdf_rent_receipt', :as => :test_pdf_rent_receipt
    get 'search_rent_charge', :as => :search_rent_charge
    get 'search_common_expense_subunit', :as => :search_common_expense_subunit
    post 'search_id_for_rent_charge' => 'administrators#search_id_for_rent_charge', :as => :search_id_for_rent_charge
    post 'search_id_for_common_expense_subunit' => 'administrators#search_id_for_common_expense_subunit', :as => :search_id_for_common_expense_subunit
    get 'check_if_common_expense_property_for_period_is_issued' => 'administrators#check_if_common_expense_property_for_period_is_issued'
    get 'edit_renter_profile/:id' => 'administrators#edit_renter_profile', :as => :edit_renter_profile
    get 'edit_owner_profile/:id' => 'administrators#edit_owner_profile', :as => :edit_owner_profile
    put 'update_renter_registry/:renter_id' => 'administrators#update_renter_registry', :as => :update_renter_registry
    put 'update_owner_registry/:owner_id' => 'administrators#update_owner_registry', :as => :update_owner_registry
  end

  scope path: '/renters', controller: :renters do
    get 'dashboard' => 'renters#dashboard', :as => :renters_dashboard
    get 'index' => 'renters#index', :as => :renters_index
    get 'subunits_for_renter', :as => :subunits_for_renter
    get 'properties_for_renter', :as => :properties_for_renter
  end

  scope path: '/owners', controller: :owners do
    get 'dashboard' => 'owners#dashboard', :as => :owners_dashboard
    get 'index' => 'owners#index', :as => :owners_index
    get 'subunits_for_owner', :as => :subunits_for_owner
    get 'properties_for_owner', :as => :properties_for_owner
  end
end

app/models/common_expense_payment.rb
class CommonExpensePayment < ActiveRecord::Base
  belongs_to :subunit
  belongs_to :renter
  belongs_to :common_expense_subunit
  belongs_to :payment_method

  has_attached_file :receipt
  validates_attachment_content_type :receipt, content_type: ['application/pdf']
end

app/controllers/common_expense_payments_controller.rb
class CommonExpensePaymentsController < ApplicationController
  before_action :set_common_expense_payment, only: [:show, :edit, :update, :destroy]

  # GET /common_expense_payments
  # GET /common_expense_payments.json
  def index
    @common_expense_payments = CommonExpensePayment.all
  end

  # GET /common_expense_payments/1
  # GET /common_expense_payments/1.json
  def show
  end

  # GET /common_expense_payments/new
  def new
    @common_expense_subunit = CommonExpenseSubunit.find(params[:common_expense_subunit_id])
    @common_expense_payment = CommonExpensePayment.new
  end

  # GET /common_expense_payments/1/edit
  def edit
  end

  # POST /common_expense_payments
  # POST /common_expense_payments.json
  def create
    @common_expense_payment = CommonExpensePayment.new(common_expense_payment_params)

    respond_to do |format|
      if @common_expense_payment.save

        @common_expense_payment.common_expense_subunit.payed = true
        @common_expense_payment.common_expense_subunit.save!

        @common_expense_subunit = @common_expense_payment.common_expense_subunit
        @subunit = @common_expense_subunit.subunit
        @property = @subunit.property
        @renter = @subunit.renter

        @qrcode = RQRCode::QRCode.new("http://github.com/").as_html

        # create a pdf from a string
        @pdf_string = render_to_string template: 'administrators/pdf_common_expense_payment', layout: 'layouts/pdf.html.erb', encoding: 'utf-8'

        # When the payment is saved, send mail to renter
        CreatedCommonExpensePaymentJob.set(wait: 5.seconds).perform_later(@common_expense_payment, @common_expense_subunit, @renter, @subunit, @property, @qrcode, @pdf_string)

        # Save the receipt to the system
        @common_expense_payment_id = @common_expense_payment.id
        CreateCommonExpensePaymentReceiptJob.set(wait: 5.seconds).perform_later(@common_expense_payment_id, @pdf_string)

        format.html { redirect_to subunit_path(@common_expense_payment.subunit), notice: 'Common expense payment was successfully created.' }
        format.json { render :show, status: :created, location: @common_expense_payment }
      else
        format.html { render :new }
        format.json { render json: @common_expense_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /common_expense_payments/1
  # PATCH/PUT /common_expense_payments/1.json
  def update
    respond_to do |format|
      if @common_expense_payment.update(common_expense_payment_params)
        format.html { redirect_to @common_expense_payment, notice: 'Common expense payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @common_expense_payment }
      else
        format.html { render :edit }
        format.json { render json: @common_expense_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /common_expense_payments/1
  # DELETE /common_expense_payments/1.json
  def destroy
    ## Get the id of subunit in order to redirect once payment is deleted
    subunit = @common_expense_payment.subunit

    ## As payment is being deleted, change status of common expense charge to false
    common_expense_subunit = @common_expense_payment.common_expense_subunit
    common_expense_subunit.payed = false
    common_expense_subunit.save!

    @common_expense_payment.destroy
    respond_to do |format|
      format.html { redirect_to subunit_path(subunit), notice: 'Common expense payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_common_expense_payment
      @common_expense_payment = CommonExpensePayment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def common_expense_payment_params
      params.require(:common_expense_payment).permit(:renter_id, :subunit_id, :amount, :payment_method_id, :common_expense_subunit_id, :receipt_number, :payment_date, :payment_method)
    end
end

app/helpers/common_expense_payments_helper.rb
module CommonExpensePaymentsHelper
end

app/views/common_expense_payments/_form.html.erb
<%= form_for(@common_expense_payment) do |f| %>
  <% if @common_expense_payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@common_expense_payment.errors.count, "error") %> prohibited this common_expense_payment from being saved:</h2>

      <ul>
      <% @common_expense_payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :renter_id %><br>
    <%= f.number_field :renter_id %>
  </div>
  <div class="field">
    <%= f.label :subunit_id %><br>
    <%= f.number_field :subunit_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :payment_method_id %><br>
    <%= f.number_field :payment_method_id %>
  </div>
  <div class="field">
    <%= f.label :common_expense_subunit_id %><br>
    <%= f.number_field :common_expense_subunit_id %>
  </div>
  <div class="field">
    <%= f.label :receipt_number %><br>
    <%= f.text_field :receipt_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/common_expense_payments/edit.html.erb
<%= render('transversals/navbar_admin') %>
<div class="sub-nav"></div>

<h1 class="text-center">Editando pago</h1>

<div class="container">
  <%= form_for(@common_expense_payment) do |f| %>
    <% if @common_expense_payment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@common_expense_payment.errors.count, "error") %> prohibited this common_expense_payment from being saved:</h2>

        <ul>
        <% @common_expense_payment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :renter_id %>
    <%= f.hidden_field :subunit_id %>
    <%= f.hidden_field :common_expense_subunit_id %>

    <div class="form-div col-md-6 col-md-offset-3">
      <%= f.label :amount, "MONTO", class: "input-header" %><br>
      <%= f.text_field :amount, class: "form-control" %>
    </div>
    <div class="form-div col-md-6 col-md-offset-3">
      <%= f.label :payment_method_id, "MÉTODO PAGO", class: "input-header" %><br>
      <%= f.collection_select :payment_method_id, PaymentMethod.order(:name), :id, :name, {}, class: "form-control" %>
    </div>
    <div class="form-div col-md-6 col-md-offset-3">
      <%= f.label :receipt_number, "RECIBO", class: "input-header" %><br>
      <%= f.text_field :receipt_number, class: "form-control" %>
    </div>
    <div class="form-div col-md-6 col-md-offset-3">
      <%= f.submit "ACTUALIZAR REGISTRO", class: "btn btn-default btn-block action-button aquamarine-button" %>
    </div>
  <% end %>

  <div class="form-div col-md-6 col-md-offset-3">
    <%= link_to("ELIMINAR REGISTRO", @common_expense_payment, method: :delete, data: { confirm: 'Esta segúro que desea eliminar el registro?' }, class: "btn btn-default btn-block action-button crimson-button") %>
  </div>
</div>

app/views/common_expense_payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Common Expense Payments</h1>

<table>
  <thead>
    <tr>
      <th>Renter</th>
      <th>Subunit</th>
      <th>Amount</th>
      <th>Payment method</th>
      <th>Common expense subunit</th>
      <th>Receipt number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @common_expense_payments.each do |common_expense_payment| %>
      <tr>
        <td><%= common_expense_payment.renter_id %></td>
        <td><%= common_expense_payment.subunit_id %></td>
        <td><%= common_expense_payment.amount %></td>
        <td><%= common_expense_payment.payment_method_id %></td>
        <td><%= common_expense_payment.common_expense_subunit_id %></td>
        <td><%= common_expense_payment.receipt_number %></td>
        <td><%= link_to 'Show', common_expense_payment %></td>
        <td><%= link_to 'Edit', edit_common_expense_payment_path(common_expense_payment) %></td>
        <td><%= link_to 'Destroy', common_expense_payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Common expense payment', new_common_expense_payment_path %>

app/views/common_expense_payments/new.html.erb
<%= render("transversals/navbar_admin") %>
<h1 class="text-center">Registro de Pago</h1>
<h3 class="text-center">Gasto Común <%= @common_expense_subunit.subunit.address_and_number %></h3>
<h3 class="text-center">Periodo: <%= @common_expense_subunit.period.strftime("%m/%Y") %></h3>

<div class="container">
  <%= form_for(@common_expense_payment) do |f| %>
    <% if @common_expense_payment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@common_expense_payment.errors.count, "error") %> prohibited this common_expense_payment from being saved:</h2>

        <ul>
        <% @common_expense_payment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :renter_id, :value => @common_expense_subunit.subunit.renter.id %>
    <%= f.hidden_field :subunit_id, :value => @common_expense_subunit.subunit.id %>
    <%= f.hidden_field :common_expense_subunit_id, :value => @common_expense_subunit.id %>

    <div class="form-div col-md-6 col-md-offset-3">
      <%= f.label :amount, "MONTO", class: "input-header" %><br>
      <%= f.text_field :amount, :value => @common_expense_subunit.total, class: "form-control" %>
    </div>
    <div class="form-div col-md-6 col-md-offset-3">
        <%= f.label :payment_date, "FECHA PAGO", class: "input-header" %><br>
        <%= f.date_select :payment_date, class: "form-control" %>
    </div>
    <div class="form-div col-md-6 col-md-offset-3">
      <%= f.label :payment_method_id, "MÉTODO PAGO", class: "input-header" %><br>
      <%= f.collection_select :payment_method_id, PaymentMethod.order(:name), :id, :name, {}, class: "form-control" %>
    </div>
    <div class="form-div col-md-6 col-md-offset-3">
      <%= f.label :receipt_number, "RECIBO", class: "input-header" %><br>
      <%= f.text_field :receipt_number, class: "form-control" %>
    </div>
    <div class="form-div col-md-6 col-md-offset-3">
      <%= f.submit "REGISTRAR", class: "btn btn-default btn-block action-button aquamarine-button" %>
    </div>
  <% end %>
</div>

app/views/common_expense_payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Renter:</strong>
  <%= @common_expense_payment.renter_id %>
</p>

<p>
  <strong>Subunit:</strong>
  <%= @common_expense_payment.subunit_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @common_expense_payment.amount %>
</p>

<p>
  <strong>Payment method:</strong>
  <%= @common_expense_payment.payment_method_id %>
</p>

<p>
  <strong>Common expense subunit:</strong>
  <%= @common_expense_payment.common_expense_subunit_id %>
</p>

<p>
  <strong>Receipt number:</strong>
  <%= @common_expense_payment.receipt_number %>
</p>

<%= link_to 'Edit', edit_common_expense_payment_path(@common_expense_payment) %> |
<%= link_to 'Back', common_expense_payments_path %>